### ISSUE TITLE
error

### ISSUE THREAD

**Issue by muthupandyN** [MrJay10/banking-faq-bot#2]
Traceback (most recent call last):
  File "C:\Users\muthupandy\AppData\Local\Programs\Python\Python35\myi.py", line 67, in <module>
    class_ = le.inverse_transform(model.predict(t_usr)[0])
  File "C:\Users\muthupandy\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\preprocessing\label.py", line 273, in inverse_transform
    y = column_or_1d(y, warn=True)
  File "C:\Users\muthupandy\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\utils\validation.py", line 797, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()
 

please  help

**Comment by AdroitAnandAI** [comment]
Modify the code as below. It will work.

        class_ = le.inverse_transform(model.predict(t_usr))
        questionset = data[data['Class']==class_[0]]

**Comment by Seeumt** [comment]
Wonderful!
