### ISSUE TITLE
Error!!

### ISSUE THREAD

**Issue by pramodkumishra** [MrJay10/banking-faq-bot#4]
Traceback (most recent call last):
  File "Bank FAQbot.py", line 158, in <module>
    chat()
  File "Bank FAQbot.py", line 113, in chat
    class_ = le.inverse_transform(model.predict(t_usr)[0])
  File "C:\Users\M1042421\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\preprocessing\label.py", line 273, in inverse_transform
    y = column_or_1d(y, warn=True)
  File "C:\Users\M1042421\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\validation.py", line 760, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()

**Comment by AdroitAnandAI** [comment]
Modify the code as below. It will work.

        class_ = le.inverse_transform(model.predict(t_usr))
        questionset = data[data['Class']==class_[0]]
